# Generated by Django 5.1.2 on 2024-10-29 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('cars_name', models.CharField(max_length=32)),
                ('cars_name_en', models.CharField(max_length=32, null=True)),
                ('cars_name_ru', models.CharField(max_length=32, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('color_en', models.CharField(blank=True, max_length=30, null=True)),
                ('color_ru', models.CharField(blank=True, max_length=30, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('year', models.PositiveIntegerField()),
                ('type_change', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, null=True, upload_to='vid/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.marka')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=16, unique=True)),
                ('marka_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.marka')),
            ],
        ),
    ]
